import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import data from '../public/wcag21_embeddings.json'

interface TreeNode {
  link_name: string;
  link_href: string;
  section_text: string;
  children: TreeNode[];
  secno: string | null;
  depth: number;
}


const TreeListView = (t: TreeNode) => {
  return (
    <li>
      <a href={t.link_href}>{t.link_name}</a>
      <ol>
        -{t.children.map(tsub => TreeListView(tsub))}
      </ol>
    </li>
  )
  // TODO: section text too
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Accessize</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ol>
          {data.children.map(t => TreeListView(t))}
        </ol>
      </main>
    </div>
  )
}

export default Home
